# hugo.toml

# Basic configuration
baseURL = 'https://s4ch.github.io'
languageCode = 'en-us'
title = 'CyFun'
#theme = "paper"
theme = "Papermod"
paginate = 5

# Build options
buildDrafts = false
buildExpired = false
buildFuture = false

# Miscellaneous
enableGitInfo = true
enableEmoji = true
