# menus.toml

[[main]]
	identifier = "about-me"
	name = "About"
	url = "/about/"
	weight = 10
[[main]]
	identifier = "contact-me"
	name = "Contact"
	url = "/contact/"
	weight = 10
[[main]]
	identifier = "research"
	name = "Research"
	url = "/research/"
	weight = 15
[[main]]
	identifier = "archives"
	name = "Archives"
	url = "/archives"
	weight = 16
[[main]]
	identifier = "writeups"
	name = "Writeups"
	url = "/writeups/"
	weight = 20
	[[main]]
		identifier = "writeups-hackthebox"
		name = "HackTheBox"
		url = "/writeups/hackthebox/"
		parent = "writeups"
		weight = 10
	[[main]]
		identifier = "writeups-tryhackme"
		name = "TryHackMe"
		url = "/writeups/tryhackme/"
		parent = "writeups"
		weight = 20
