# SEO information
keywords = [
	"Cybersecurity",
	"Blog",
	"Portfolio"
]

# Appearance
env = 'production' 	# Enable OpenGraph protocol
#images = "/link"

defaultTheme = 'auto'
DisableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

# Home page mode
mode = "home"
displayFullLangName = true
mainSections = ["research"]
ShowAllPagesInArchive = true

# Custom CSS
[assets]
disableHLJS = false

[homeInfoParams]
Title = "[~]$ whoami?"
Content = """
Hi, I'm Sachin (@cyfun). I'm a budding security researcher with interests in threat hunting, reverse engineering, pwning, web and network security.


"""

[[social]]
name = "github"
url = "https://github.com/s4ch"

[[social]]
name = "linkedin"
url = "https://www.linkedin.com/in/sachinkumardhaka/"

[[social]]
name = "More information"
url = "/contact"
