# SEO information
keywords = [
	"Cybersecurity",
	"Blog",
	"Portfolio"
]

# Appearance
env = 'production' 	# Enable OpenGraph protocol
#images = "/link"

defaultTheme = 'auto'
DisableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

# Home page mode
mode = "home"
displayFullLangName = true
mainSections = ["research"]

[homeInfoParams]
Title = "[~]$ whoami?"
Content = """
Hi, I'm Sachin (@cyfun). I'm a budding security researcher with interests in threat hunting, reverse engineering, pwning, web and network security.

**Recent Research Highlights:**
- 🔍 OAuth weaponization in Microsoft Outlook attacks
- 🛡️ eBPF JIT compiler security mechanisms analysis  
- 🔧 Novel Linux kernel UAF mitigation techniques

[ [About](/about) ] [ [Research](/research) ] [ [Archives](/archives) ] [ [Writeups](/writeups) ] [ [Contact](/contact) ]
"""

[[social]]
name = "github"
url = "https://github.com/s4ch"

[[social]]
name = "linkedin"
url = "https://www.linkedin.com/in/sachinkumardhaka/"

[[social]]
name = "More information"
url = "/contact"
